// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package ws;


public class ArrayOfAsignaturaInscrita {
    protected ws.AsignaturaInscrita[] asignaturaInscrita;
    
    public ArrayOfAsignaturaInscrita() {
    }
    
    public ArrayOfAsignaturaInscrita(ws.AsignaturaInscrita[] asignaturaInscrita) {
        this.asignaturaInscrita = asignaturaInscrita;
    }
    
    public ws.AsignaturaInscrita[] getAsignaturaInscrita() {
        return asignaturaInscrita;
    }
    
    public void setAsignaturaInscrita(ws.AsignaturaInscrita[] asignaturaInscrita) {
        this.asignaturaInscrita = asignaturaInscrita;
    }
}
