// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package ws;


public class Evaluaciones {
    protected double laboratorio1;
    protected double laboratorio2;
    protected double laboratorio3;
    protected double laboratorio4;
    protected double promedioLaboratorios;
    protected double pruebaObjetiva1;
    protected double pruebaObjetiva2;
    protected double pruebaObjetiva3;
    protected double pruebaObjetiva4;
    protected double promedioPruebasObjetivas;
    protected double notaFinal;
    
    public Evaluaciones() {
    }
    
    public Evaluaciones(double laboratorio1, double laboratorio2, double laboratorio3, double laboratorio4, double promedioLaboratorios, double pruebaObjetiva1, double pruebaObjetiva2, double pruebaObjetiva3, double pruebaObjetiva4, double promedioPruebasObjetivas, double notaFinal) {
        this.laboratorio1 = laboratorio1;
        this.laboratorio2 = laboratorio2;
        this.laboratorio3 = laboratorio3;
        this.laboratorio4 = laboratorio4;
        this.promedioLaboratorios = promedioLaboratorios;
        this.pruebaObjetiva1 = pruebaObjetiva1;
        this.pruebaObjetiva2 = pruebaObjetiva2;
        this.pruebaObjetiva3 = pruebaObjetiva3;
        this.pruebaObjetiva4 = pruebaObjetiva4;
        this.promedioPruebasObjetivas = promedioPruebasObjetivas;
        this.notaFinal = notaFinal;
    }
    
    public double getLaboratorio1() {
        return laboratorio1;
    }
    
    public void setLaboratorio1(double laboratorio1) {
        this.laboratorio1 = laboratorio1;
    }
    
    public double getLaboratorio2() {
        return laboratorio2;
    }
    
    public void setLaboratorio2(double laboratorio2) {
        this.laboratorio2 = laboratorio2;
    }
    
    public double getLaboratorio3() {
        return laboratorio3;
    }
    
    public void setLaboratorio3(double laboratorio3) {
        this.laboratorio3 = laboratorio3;
    }
    
    public double getLaboratorio4() {
        return laboratorio4;
    }
    
    public void setLaboratorio4(double laboratorio4) {
        this.laboratorio4 = laboratorio4;
    }
    
    public double getPromedioLaboratorios() {
        return promedioLaboratorios;
    }
    
    public void setPromedioLaboratorios(double promedioLaboratorios) {
        this.promedioLaboratorios = promedioLaboratorios;
    }
    
    public double getPruebaObjetiva1() {
        return pruebaObjetiva1;
    }
    
    public void setPruebaObjetiva1(double pruebaObjetiva1) {
        this.pruebaObjetiva1 = pruebaObjetiva1;
    }
    
    public double getPruebaObjetiva2() {
        return pruebaObjetiva2;
    }
    
    public void setPruebaObjetiva2(double pruebaObjetiva2) {
        this.pruebaObjetiva2 = pruebaObjetiva2;
    }
    
    public double getPruebaObjetiva3() {
        return pruebaObjetiva3;
    }
    
    public void setPruebaObjetiva3(double pruebaObjetiva3) {
        this.pruebaObjetiva3 = pruebaObjetiva3;
    }
    
    public double getPruebaObjetiva4() {
        return pruebaObjetiva4;
    }
    
    public void setPruebaObjetiva4(double pruebaObjetiva4) {
        this.pruebaObjetiva4 = pruebaObjetiva4;
    }
    
    public double getPromedioPruebasObjetivas() {
        return promedioPruebasObjetivas;
    }
    
    public void setPromedioPruebasObjetivas(double promedioPruebasObjetivas) {
        this.promedioPruebasObjetivas = promedioPruebasObjetivas;
    }
    
    public double getNotaFinal() {
        return notaFinal;
    }
    
    public void setNotaFinal(double notaFinal) {
        this.notaFinal = notaFinal;
    }
}
