// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package ws;


public class RecuperarAsignaturasInscritas {
    protected java.lang.String carnet;
    protected java.lang.String code;
    
    public RecuperarAsignaturasInscritas() {
    }
    
    public RecuperarAsignaturasInscritas(java.lang.String carnet, java.lang.String code) {
        this.carnet = carnet;
        this.code = code;
    }
    
    public java.lang.String getCarnet() {
        return carnet;
    }
    
    public void setCarnet(java.lang.String carnet) {
        this.carnet = carnet;
    }
    
    public java.lang.String getCode() {
        return code;
    }
    
    public void setCode(java.lang.String code) {
        this.code = code;
    }
}
