// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package ws;


public class RecuperarAsignaturasInscritasResponse {
    protected ws.ArrayOfAsignaturaInscrita recuperarAsignaturasInscritasResult;
    
    public RecuperarAsignaturasInscritasResponse() {
    }
    
    public RecuperarAsignaturasInscritasResponse(ws.ArrayOfAsignaturaInscrita recuperarAsignaturasInscritasResult) {
        this.recuperarAsignaturasInscritasResult = recuperarAsignaturasInscritasResult;
    }
    
    public ws.ArrayOfAsignaturaInscrita getRecuperarAsignaturasInscritasResult() {
        return recuperarAsignaturasInscritasResult;
    }
    
    public void setRecuperarAsignaturasInscritasResult(ws.ArrayOfAsignaturaInscrita recuperarAsignaturasInscritasResult) {
        this.recuperarAsignaturasInscritasResult = recuperarAsignaturasInscritasResult;
    }
}
