// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package ws;

public interface WsMovilSoap extends java.rmi.Remote {
	public ws.ArrayOfAsignaturaInscrita recuperarAsignaturasInscritas(java.lang.String carnet, java.lang.String code) throws java.rmi.RemoteException;

}
