// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package ws;

import javax.xml.rpc.JAXRPCException;
import javax.xml.namespace.QName;
import javax.microedition.xml.rpc.Operation;
import javax.microedition.xml.rpc.Type;
import javax.microedition.xml.rpc.ComplexType;
import javax.microedition.xml.rpc.Element;

import com.twmacinta.util.Autenticacion;

public class WsMovilSoap_Stub implements ws.WsMovilSoap, javax.xml.rpc.Stub {
	private String[] _propertyNames;
	private Object[] _propertyValues;

	public WsMovilSoap_Stub() {
		_propertyNames = new String[] {ENDPOINT_ADDRESS_PROPERTY};
		String matanga = Autenticacion.getConnectionString();
		_propertyValues = new Object[] {"http://registro.ufg.edu.sv/wsMovil/wsMovil.asmx"+matanga};
	}

	public void _setProperty(String name, Object value) {
		int size = _propertyNames.length;
		for (int i = 0; i < size; ++i) {
			if (_propertyNames[i].equals(name)) {
				_propertyValues[i] = value;
				return;
			}
		}
		// Need to expand our array for a new property
		String[] newPropNames = new String[size + 1];
		System.arraycopy(_propertyNames, 0, newPropNames, 0, size);
		_propertyNames = newPropNames;
		Object[] newPropValues = new Object[size + 1];
		System.arraycopy(_propertyValues, 0, newPropValues, 0, size);
		_propertyValues = newPropValues;

		_propertyNames[size] = name;
		_propertyValues[size] = value;
	}

	public Object _getProperty(String name) {
		for (int i = 0; i < _propertyNames.length; ++i) {
			if (_propertyNames[i].equals(name)) {
				return _propertyValues[i];
			}
		}
		if (ENDPOINT_ADDRESS_PROPERTY.equals(name) || USERNAME_PROPERTY.equals(name) || PASSWORD_PROPERTY.equals(name)) {
			return null;
		}
		if (SESSION_MAINTAIN_PROPERTY.equals(name)) {
			return new java.lang.Boolean(false);
		}
		throw new JAXRPCException("Stub does not recognize property: "+name);
	}

	protected void _prepOperation(Operation op) {
		for (int i = 0; i < _propertyNames.length; ++i) {
			op.setProperty(_propertyNames[i], _propertyValues[i].toString());
		}
	}

	// 
	//  Begin user methods
	// 

	public ws.ArrayOfAsignaturaInscrita recuperarAsignaturasInscritas(java.lang.String carnet, java.lang.String code) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[2];
		inputObject[0] = carnet;
		inputObject[1] = code;

		Operation op = Operation.newInstance(_qname_RecuperarAsignaturasInscritas, _type_RecuperarAsignaturasInscritas, _type_RecuperarAsignaturasInscritasResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "http://imovil.registro.ufg.edu.sv/RecuperarAsignaturasInscritas");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		ws.ArrayOfAsignaturaInscrita result;
		// Convert the result into the right Java type.
		// Unwrapped return value
		Object[] recuperarAsignaturasInscritasResultObj = (Object[]) ((Object[])resultObj)[0];
		if (recuperarAsignaturasInscritasResultObj == null) {
			result = null;
		} else {
			result = new ws.ArrayOfAsignaturaInscrita();
			ws.AsignaturaInscrita[] asignaturaInscritaArray;
			Object[] asignaturaInscritaObj = (Object[]) recuperarAsignaturasInscritasResultObj[0];
			if (asignaturaInscritaObj == null) {
				asignaturaInscritaArray = null;
			} else {
				int asignaturaInscritaArraySize = asignaturaInscritaObj.length;
				asignaturaInscritaArray = new ws.AsignaturaInscrita[asignaturaInscritaArraySize];
				for (int asignaturaInscritaArrayIndex = 0; 
					asignaturaInscritaArrayIndex < asignaturaInscritaArraySize; 
					++asignaturaInscritaArrayIndex) {
					if (asignaturaInscritaObj[asignaturaInscritaArrayIndex] == null) {
						asignaturaInscritaArray[asignaturaInscritaArrayIndex] = null;
					} else {
						asignaturaInscritaArray[asignaturaInscritaArrayIndex] = new ws.AsignaturaInscrita();
						java.lang.String string;
						Object idAsignaturaObj = ((Object[])asignaturaInscritaObj[asignaturaInscritaArrayIndex])[0];
						string = (java.lang.String)idAsignaturaObj;
						asignaturaInscritaArray[asignaturaInscritaArrayIndex].setIdAsignatura(string);
						java.lang.String string2;
						Object nombreAsignaturaObj = ((Object[])asignaturaInscritaObj[asignaturaInscritaArrayIndex])[1];
						string2 = (java.lang.String)nombreAsignaturaObj;
						asignaturaInscritaArray[asignaturaInscritaArrayIndex].setNombreAsignatura(string2);
						java.lang.String string3;
						Object grupoObj = ((Object[])asignaturaInscritaObj[asignaturaInscritaArrayIndex])[2];
						string3 = (java.lang.String)grupoObj;
						asignaturaInscritaArray[asignaturaInscritaArrayIndex].setGrupo(string3);
						ws.Evaluaciones evaluaciones;
						Object[] evaluacionesObj = (Object[]) ((Object[])asignaturaInscritaObj[asignaturaInscritaArrayIndex])[3];
						if (evaluacionesObj == null) {
							evaluaciones = null;
						} else {
							evaluaciones = new ws.Evaluaciones();
							double a_double;
							Object laboratorio1Obj = evaluacionesObj[0];
							a_double = ((java.lang.Double)laboratorio1Obj).doubleValue();
							evaluaciones.setLaboratorio1(a_double);
							double a_double2;
							Object laboratorio2Obj = evaluacionesObj[1];
							a_double2 = ((java.lang.Double)laboratorio2Obj).doubleValue();
							evaluaciones.setLaboratorio2(a_double2);
							double a_double3;
							Object laboratorio3Obj = evaluacionesObj[2];
							a_double3 = ((java.lang.Double)laboratorio3Obj).doubleValue();
							evaluaciones.setLaboratorio3(a_double3);
							double a_double4;
							Object laboratorio4Obj = evaluacionesObj[3];
							a_double4 = ((java.lang.Double)laboratorio4Obj).doubleValue();
							evaluaciones.setLaboratorio4(a_double4);
							double a_double5;
							Object promedioLaboratoriosObj = evaluacionesObj[4];
							a_double5 = ((java.lang.Double)promedioLaboratoriosObj).doubleValue();
							evaluaciones.setPromedioLaboratorios(a_double5);
							double a_double6;
							Object pruebaObjetiva1Obj = evaluacionesObj[5];
							a_double6 = ((java.lang.Double)pruebaObjetiva1Obj).doubleValue();
							evaluaciones.setPruebaObjetiva1(a_double6);
							double a_double7;
							Object pruebaObjetiva2Obj = evaluacionesObj[6];
							a_double7 = ((java.lang.Double)pruebaObjetiva2Obj).doubleValue();
							evaluaciones.setPruebaObjetiva2(a_double7);
							double a_double8;
							Object pruebaObjetiva3Obj = evaluacionesObj[7];
							a_double8 = ((java.lang.Double)pruebaObjetiva3Obj).doubleValue();
							evaluaciones.setPruebaObjetiva3(a_double8);
							double a_double9;
							Object pruebaObjetiva4Obj = evaluacionesObj[8];
							a_double9 = ((java.lang.Double)pruebaObjetiva4Obj).doubleValue();
							evaluaciones.setPruebaObjetiva4(a_double9);
							double a_double10;
							Object promedioPruebasObjetivasObj = evaluacionesObj[9];
							a_double10 = ((java.lang.Double)promedioPruebasObjetivasObj).doubleValue();
							evaluaciones.setPromedioPruebasObjetivas(a_double10);
							double a_double11;
							Object notaFinalObj = evaluacionesObj[10];
							a_double11 = ((java.lang.Double)notaFinalObj).doubleValue();
							evaluaciones.setNotaFinal(a_double11);
						}
						asignaturaInscritaArray[asignaturaInscritaArrayIndex].setEvaluaciones(evaluaciones);
					}
				}
			}
			result.setAsignaturaInscrita(asignaturaInscritaArray);
		}
		return result;
	}
	// 
	//  End user methods
	// 

	protected static final QName _qname_AsignaturaInscrita = new QName("http://imovil.registro.ufg.edu.sv/", "AsignaturaInscrita");
	protected static final QName _qname_RecuperarAsignaturasInscritas = new QName("http://imovil.registro.ufg.edu.sv/", "RecuperarAsignaturasInscritas");
	protected static final QName _qname_RecuperarAsignaturasInscritasResponse = new QName("http://imovil.registro.ufg.edu.sv/", "RecuperarAsignaturasInscritasResponse");
	protected static final QName _qname_RecuperarAsignaturasInscritasResult = new QName("http://imovil.registro.ufg.edu.sv/", "RecuperarAsignaturasInscritasResult");
	protected static final QName _qname_carnet = new QName("http://imovil.registro.ufg.edu.sv/", "carnet");
	protected static final QName _qname_code = new QName("http://imovil.registro.ufg.edu.sv/", "code");
	protected static final QName _qname_evaluaciones = new QName("http://imovil.registro.ufg.edu.sv/", "evaluaciones");
	protected static final QName _qname_grupo = new QName("http://imovil.registro.ufg.edu.sv/", "grupo");
	protected static final QName _qname_idAsignatura = new QName("http://imovil.registro.ufg.edu.sv/", "idAsignatura");
	protected static final QName _qname_laboratorio1 = new QName("http://imovil.registro.ufg.edu.sv/", "laboratorio1");
	protected static final QName _qname_laboratorio2 = new QName("http://imovil.registro.ufg.edu.sv/", "laboratorio2");
	protected static final QName _qname_laboratorio3 = new QName("http://imovil.registro.ufg.edu.sv/", "laboratorio3");
	protected static final QName _qname_laboratorio4 = new QName("http://imovil.registro.ufg.edu.sv/", "laboratorio4");
	protected static final QName _qname_nombreAsignatura = new QName("http://imovil.registro.ufg.edu.sv/", "nombreAsignatura");
	protected static final QName _qname_notaFinal = new QName("http://imovil.registro.ufg.edu.sv/", "notaFinal");
	protected static final QName _qname_promedioLaboratorios = new QName("http://imovil.registro.ufg.edu.sv/", "promedioLaboratorios");
	protected static final QName _qname_promedioPruebasObjetivas = new QName("http://imovil.registro.ufg.edu.sv/", "promedioPruebasObjetivas");
	protected static final QName _qname_pruebaObjetiva1 = new QName("http://imovil.registro.ufg.edu.sv/", "pruebaObjetiva1");
	protected static final QName _qname_pruebaObjetiva2 = new QName("http://imovil.registro.ufg.edu.sv/", "pruebaObjetiva2");
	protected static final QName _qname_pruebaObjetiva3 = new QName("http://imovil.registro.ufg.edu.sv/", "pruebaObjetiva3");
	protected static final QName _qname_pruebaObjetiva4 = new QName("http://imovil.registro.ufg.edu.sv/", "pruebaObjetiva4");
	protected static final Element _type_RecuperarAsignaturasInscritas;
	protected static final Element _type_RecuperarAsignaturasInscritasResponse;
	static {
		// Create all of the Type's that this stub uses, once.
		Element _type_carnet;
		_type_carnet = new Element(_qname_carnet, Type.STRING, 0, 1, false);
		Element _type_code;
		_type_code = new Element(_qname_code, Type.STRING, 0, 1, false);
		ComplexType _complexType_recuperarAsignaturasInscritas;
		_complexType_recuperarAsignaturasInscritas = new ComplexType();
		_complexType_recuperarAsignaturasInscritas.elements = new Element[2];
		_complexType_recuperarAsignaturasInscritas.elements[0] = _type_carnet;
		_complexType_recuperarAsignaturasInscritas.elements[1] = _type_code;
		_type_RecuperarAsignaturasInscritas = new Element(_qname_RecuperarAsignaturasInscritas, _complexType_recuperarAsignaturasInscritas);
		Element _type_idAsignatura;
		_type_idAsignatura = new Element(_qname_idAsignatura, Type.STRING, 0, 1, false);
		Element _type_nombreAsignatura;
		_type_nombreAsignatura = new Element(_qname_nombreAsignatura, Type.STRING, 0, 1, false);
		Element _type_grupo;
		_type_grupo = new Element(_qname_grupo, Type.STRING, 0, 1, false);
		Element _type_laboratorio1;
		_type_laboratorio1 = new Element(_qname_laboratorio1, Type.DOUBLE);
		Element _type_laboratorio2;
		_type_laboratorio2 = new Element(_qname_laboratorio2, Type.DOUBLE);
		Element _type_laboratorio3;
		_type_laboratorio3 = new Element(_qname_laboratorio3, Type.DOUBLE);
		Element _type_laboratorio4;
		_type_laboratorio4 = new Element(_qname_laboratorio4, Type.DOUBLE);
		Element _type_promedioLaboratorios;
		_type_promedioLaboratorios = new Element(_qname_promedioLaboratorios, Type.DOUBLE);
		Element _type_pruebaObjetiva1;
		_type_pruebaObjetiva1 = new Element(_qname_pruebaObjetiva1, Type.DOUBLE);
		Element _type_pruebaObjetiva2;
		_type_pruebaObjetiva2 = new Element(_qname_pruebaObjetiva2, Type.DOUBLE);
		Element _type_pruebaObjetiva3;
		_type_pruebaObjetiva3 = new Element(_qname_pruebaObjetiva3, Type.DOUBLE);
		Element _type_pruebaObjetiva4;
		_type_pruebaObjetiva4 = new Element(_qname_pruebaObjetiva4, Type.DOUBLE);
		Element _type_promedioPruebasObjetivas;
		_type_promedioPruebasObjetivas = new Element(_qname_promedioPruebasObjetivas, Type.DOUBLE);
		Element _type_notaFinal;
		_type_notaFinal = new Element(_qname_notaFinal, Type.DOUBLE);
		ComplexType _complexType_evaluaciones;
		_complexType_evaluaciones = new ComplexType();
		_complexType_evaluaciones.elements = new Element[11];
		_complexType_evaluaciones.elements[0] = _type_laboratorio1;
		_complexType_evaluaciones.elements[1] = _type_laboratorio2;
		_complexType_evaluaciones.elements[2] = _type_laboratorio3;
		_complexType_evaluaciones.elements[3] = _type_laboratorio4;
		_complexType_evaluaciones.elements[4] = _type_promedioLaboratorios;
		_complexType_evaluaciones.elements[5] = _type_pruebaObjetiva1;
		_complexType_evaluaciones.elements[6] = _type_pruebaObjetiva2;
		_complexType_evaluaciones.elements[7] = _type_pruebaObjetiva3;
		_complexType_evaluaciones.elements[8] = _type_pruebaObjetiva4;
		_complexType_evaluaciones.elements[9] = _type_promedioPruebasObjetivas;
		_complexType_evaluaciones.elements[10] = _type_notaFinal;
		Element _type_evaluaciones;
		_type_evaluaciones = new Element(_qname_evaluaciones, _complexType_evaluaciones, 0, 1, false);
		ComplexType _complexType_asignaturaInscrita;
		_complexType_asignaturaInscrita = new ComplexType();
		_complexType_asignaturaInscrita.elements = new Element[4];
		_complexType_asignaturaInscrita.elements[0] = _type_idAsignatura;
		_complexType_asignaturaInscrita.elements[1] = _type_nombreAsignatura;
		_complexType_asignaturaInscrita.elements[2] = _type_grupo;
		_complexType_asignaturaInscrita.elements[3] = _type_evaluaciones;
		Element _type_AsignaturaInscrita;
		_type_AsignaturaInscrita = new Element(_qname_AsignaturaInscrita, _complexType_asignaturaInscrita, 0, -1, true);
		ComplexType _complexType_arrayOfAsignaturaInscrita;
		_complexType_arrayOfAsignaturaInscrita = new ComplexType();
		_complexType_arrayOfAsignaturaInscrita.elements = new Element[1];
		_complexType_arrayOfAsignaturaInscrita.elements[0] = _type_AsignaturaInscrita;
		Element _type_RecuperarAsignaturasInscritasResult;
		_type_RecuperarAsignaturasInscritasResult = new Element(_qname_RecuperarAsignaturasInscritasResult, _complexType_arrayOfAsignaturaInscrita, 0, 1, false);
		ComplexType _complexType_recuperarAsignaturasInscritasResponse;
		_complexType_recuperarAsignaturasInscritasResponse = new ComplexType();
		_complexType_recuperarAsignaturasInscritasResponse.elements = new Element[1];
		_complexType_recuperarAsignaturasInscritasResponse.elements[0] = _type_RecuperarAsignaturasInscritasResult;
		_type_RecuperarAsignaturasInscritasResponse = new Element(_qname_RecuperarAsignaturasInscritasResponse, _complexType_recuperarAsignaturasInscritasResponse);
	}

}
